### ISSUE TITLE
Problem with generating movie

### ISSUE THREAD

**Issue by saltwat5r** [cameronehrlich/CEMovieMaker#1]
Hi!
I have a problem with generating a movie.
This is my method for creating a movie:

```
+ (NSURL *)processMovieWithPhotos:(NSArray *)photosArray
{
    __block NSURL *finalMovieURL = nil;
    NSMutableArray *frames = [[NSMutableArray alloc] init];

    NSArray *resizedPhotosArray = [self resizedPhotosToCreateMovieFromArray:photosArray];
    UIImage *onePhoto = resizedPhotosArray[0];

    NSDictionary *settings = [CEMovieMaker videoSettingsWithCodec:AVVideoCodecH264 withWidth:onePhoto.size.width andHeight:onePhoto.size.height];
    CEMovieMaker *movieMaker = [[CEMovieMaker alloc] initWithSettings:settings];
    [frames addObjectsFromArray:resizedPhotosArray];

    [movieMaker createMovieFromImages:[frames copy] withCompletion:^(BOOL success, NSURL *fileURL){
        if (success) {
            finalMovieURL = fileURL;
        }
    }];

    return finalMovieURL;
}
```

Method resizedPhotosToCreateMovieFromArray: resizes photos proportion for height of 1920 and returns photos array.

The problem is that Movie file size is 0 kbytes and in method createMovieFromImages:withCompletion: success is equal to NO.
Any idea for this issue?

**Comment by cameronehrlich** [comment]
Hey! I'll take a quick look through my code and see what might be causing the issue.  Could you post your `resizedPhotosToCreateMovieFromArray:` implementation here so I could glance over that as well?

**Comment by cameronehrlich** [comment]
@saltwat5r looks like I never implemented `success` in the callback.  I pushed my most recent changes to master, but I don't think they will fix your problem. Maybe you could share with me what you are working on and I can help you debug it?  This was a quick hack and is not production ready, but if you'd like to help me get it there I'm down!

**Comment by cameronehrlich** [comment]
... maybe making the CEMovieMaker a (strong) property:

```
@property (nonatomic, strong) CEMovieMaker *movieMaker;
```

also, createMovieFromImages:withCompletion: runs asynchronously, so you are always going to return `nil` because you are returning from the function before the completion block is called and the `finalMovieURL = fileURL;` assignment hasn't happened yet.

**Comment by kierobinson1** [comment]
Hi!
I'm having a problem with changing the length of time that each image stays on the screen. For example I'd like the user to choose an amount of time, in seconds, and the image would be on the screen for that length of time. I've tried changing the _frameTime variable, but to no avail. It's set default to CMTimeMake(1,1) which places each image on the screen for 1 second. However if I change it to another number, such as   _frameTime = CMTimeMake(10, 2); this should show each image for 5 seconds, however it only applies to the first image, then the rest of the images are shown for a minimal length of time.

Thanks
Kieran
