### ISSUE TITLE
looping video

### ISSUE THREAD

**Issue by mgiraldo** [cameronehrlich/CEMovieMaker#12]
is it possible to create a looping video? I want to have a similar effect as an animated GIF but with video files.

**Comment by cameronehrlich** [comment]
Yeah.  Just throw the frames for a single loop into an array, and then create a new array of those images by adding the contents of your original array `n` times. 

``` objective-c
    NSArray *framesForSingleLoop = @[[UIImage imageNamed:@"image1"],
                                     [UIImage imageNamed:@"image2"],
                                     [UIImage imageNamed:@"image3"]];

    NSUInteger numberOfLoops = 10;

    NSMutableArray *finalFrames = [NSMutableArray new];

    for (NSUInteger i = 0; i < numberOfLoops; i++) {
        [finalFrames addObjectsFromArray:framesForSingleLoop];
    }

    // finalFrames now has all the images in it, feed it into CEMovieMaker

```

**Comment by mgiraldo** [comment]
got it. i was wondering if there was a parameter i could set to the QuickTime movie or something for this. but i this also works as an alternative.

thanks!

**Comment by cameronehrlich** [comment]
You can configure looping with `MPMoviePlayerViewController` and `AVPlayer`.  Also, A great player library by the guys at Vimeo I've been using recently: https://github.com/vimeo/VIMVideoPlayer
