### ISSUE TITLE
Images turned 90 counterclockwise 

### ISSUE THREAD

**Issue by jjeon5** [cameronehrlich/CEMovieMaker#6]
I have an array of square images that are perfectly fine but when I create a movie from them, the images are turned 90 degrees counterclockwise. Any idea why this is happening?
Thanks!

**Comment by cameronehrlich** [comment]
Check what the imageOrientation is on the images!

**Comment by cameronehrlich** [comment]
@jeon97 did you figure it out?

**Comment by royherma** [comment]
same issue...also, how would you recommend setting the time between image switching? right now its just iterating through them all super fast...

thanks

**Comment by heinst** [comment]
Having the exact same issue. Im using your library in Swift 2 with the bridging header. Everything else works fine, but the image is just landscape when it should be portrait. My `image.imageOrientation.rawValue` is 3.

```
let settings: NSDictionary = CEMovieMaker.videoSettingsWithCodec(AVVideoCodecH264, withWidth: savedImage.size.width, andHeight: savedImage.size.height)
let movieMaker = CEMovieMaker(settings: settings as! [NSObject : AnyObject])

movieMaker.createMovieFromImages(frames.copy() as! [UIImage], withCompletion: { (fileURL) -> Void in
       ......
})
```

Also the README could be updated not to include the `Bool` in the completion handler. Had to go through the commit log to see you actually took that out. 

@jeon97 Did you ever figure out a workaround?
