### ISSUE TITLE
Image Cropping in Video Output

### ISSUE THREAD

**Issue by ttseng** [cameronehrlich/CEMovieMaker#8]
Using your code, I'm able to export a video, but it seems to crop the images incorrectly.

Here is what my code looks like:

```
UIImage *resizedPhoto = [self imageWithImage:rotatedPhoto scaledToSize:CGSizeMake(704, 704)];

        // save resizedPhoto to gallery for testing
//        UIImageWriteToSavedPhotosAlbum(resizedPhoto, nil, nil, nil);

        // add image to spin array
        [_spinImages addObject:resizedPhoto];
        imgUploadedCount++;

        if(imgUploadedCount == SPIN_IMAGES){
            NSLog(@"generating video");
            NSDictionary *settings = [CEMovieMaker videoSettingsWithCodec:AVVideoCodecH264 withWidth:resizedPhoto.size.width andHeight:resizedPhoto.size.height];
            self.movieMaker = [[CEMovieMaker alloc]
                               initWithSettings:settings];

            [self.movieMaker createMovieFromImages:[_spinImages copy] withCompletion:^(NSURL *fileURL){
                NSLog(@"movie at fileURL: %@", fileURL);
}];
}
```

These are the resulting images:

![2015-07-10 10 30 53](https://cloud.githubusercontent.com/assets/519336/8620909/a56bfa46-26f0-11e5-865d-e8b8e661238f.jpg)
![2015-07-10 10 30 56](https://cloud.githubusercontent.com/assets/519336/8620910/a56ea99e-26f0-11e5-9509-3d5db64217fe.jpg)
![2015-07-10 10 31 00-1](https://cloud.githubusercontent.com/assets/519336/8620911/a5708c8c-26f0-11e5-97b2-a050173c452e.jpg)

and the resulting video:

https://dl.dropboxusercontent.com/u/1000620/2015-07-10%2010.31.00-2.mov

**Comment by ttseng** [comment]
I resolved the issue - it turned out that the images weren't resized properly before running CEMovieMaker.

**Comment by cameronehrlich** [comment]
:+1:
